SET @payment_state_check=(SELECT tc.CONSTRAINT_NAME FROM information_schema.TABLE_CONSTRAINTS tc
 JOIN information_schema.CHECK_CONSTRAINTS cc ON cc.CONSTRAINT_SCHEMA=tc.CONSTRAINT_SCHEMA AND cc.CONSTRAINT_NAME=tc.CONSTRAINT_NAME
 WHERE tc.TABLE_SCHEMA=DATABASE() AND tc.TABLE_NAME='payments' AND tc.CONSTRAINT_TYPE='CHECK' AND cc.CHECK_CLAUSE LIKE '%SIMULATED_REFUNDED%' LIMIT 1);
SET @drop_payment_check=CONCAT('ALTER TABLE payments DROP CHECK `',@payment_state_check,'`');
PREPARE payment_check_statement FROM @drop_payment_check;
EXECUTE payment_check_statement;
DEALLOCATE PREPARE payment_check_statement;
ALTER TABLE payments ADD CONSTRAINT chk_payment_state CHECK(state IN ('UNPAID','PAID','SIMULATED_PAID','SIMULATED_FAILED','SIMULATED_REFUNDED','CANCELLED','REFUND_PENDING','REFUNDED'));
SET @refund_state_check=(SELECT tc.CONSTRAINT_NAME FROM information_schema.TABLE_CONSTRAINTS tc
 JOIN information_schema.CHECK_CONSTRAINTS cc ON cc.CONSTRAINT_SCHEMA=tc.CONSTRAINT_SCHEMA AND cc.CONSTRAINT_NAME=tc.CONSTRAINT_NAME
 WHERE tc.TABLE_SCHEMA=DATABASE() AND tc.TABLE_NAME='refunds' AND tc.CONSTRAINT_TYPE='CHECK' AND cc.CHECK_CLAUSE LIKE '%SIMULATED_REFUNDED%' LIMIT 1);
SET @drop_refund_check=CONCAT('ALTER TABLE refunds DROP CHECK `',@refund_state_check,'`');
PREPARE refund_check_statement FROM @drop_refund_check;
EXECUTE refund_check_statement;
DEALLOCATE PREPARE refund_check_statement;
ALTER TABLE refunds ADD COLUMN reference VARCHAR(190),ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE refunds ADD CONSTRAINT chk_refund_state CHECK(state IN ('SIMULATED_REFUNDED','PENDING_MANUAL','REFUNDED'));
