UPDATE store_content SET content_text = 'LỤA STUDIO là cửa hàng thời trang trực tuyến trong hệ thống trình diễn đồ án quản lý shop quần áo theo kiến trúc SOA. Khách hàng có thể xem sản phẩm theo danh mục, chọn size và màu, theo dõi tồn kho, đặt hàng và quản lý đơn trên cùng một website.\n\nThông tin sản phẩm, giá bán và tình trạng còn hàng được cập nhật từ hệ thống quản lý. Ảnh sản phẩm mẫu dùng cho mục đích trình diễn.\n\nĐể được hỗ trợ về đơn hàng, vui lòng đăng nhập và gửi yêu cầu tại mục Hỗ trợ, hoặc dùng biểu mẫu ở trang Liên hệ.', updated_at = UTC_TIMESTAMP(6)
WHERE content_key = 'ABOUT' AND TRIM(content_text) = '';

UPDATE store_content SET content_text = 'Bạn có thể gửi câu hỏi qua biểu mẫu liên hệ ngay bên dưới. Nếu đã đăng nhập, hãy mở mục Hỗ trợ để tạo yêu cầu và theo dõi phản hồi.\n\nKhi hỏi về đơn hàng, vui lòng cung cấp mã đơn để nhân viên tra cứu nhanh hơn. Không gửi mật khẩu hoặc thông tin thẻ thanh toán trong nội dung liên hệ.\n\nĐịa chỉ, số điện thoại và giờ hoạt động sẽ được cửa hàng cập nhật tại đây khi có thông tin chính thức.', updated_at = UTC_TIMESTAMP(6)
WHERE content_key = 'CONTACT' AND TRIM(content_text) = '';

UPDATE store_content SET content_text = '1. Chọn sản phẩm và biến thể\nXem mô tả, ảnh, size, màu và số lượng khả dụng của từng biến thể trước khi thêm vào giỏ. Giá và tồn kho được kiểm tra lại ở máy chủ khi đặt hàng.\n\n2. Đặt hàng\nĐăng nhập, nhập thông tin người nhận và địa chỉ giao hàng, kiểm tra tổng tiền rồi xác nhận. Hệ thống không tạo đơn từ giỏ hàng trống và sử dụng mã yêu cầu để hạn chế đặt trùng khi bấm nhiều lần.\n\n3. Thanh toán\nCó thể chọn thanh toán khi nhận hàng (COD) hoặc thanh toán mô phỏng để trình diễn. Chế độ mô phỏng không thu tiền thật và không phải giao dịch ngân hàng. Đơn mô phỏng cần hoàn tất bước xác nhận trong 15 phút.\n\n4. Theo dõi và hủy đơn\nTrạng thái đơn hàng hiển thị trong mục Đơn của tôi. Khách có thể yêu cầu hủy khi đơn còn ở trạng thái cho phép; các đơn đã chuyển sang giao hàng cần liên hệ hỗ trợ.', updated_at = UTC_TIMESTAMP(6)
WHERE content_key = 'PURCHASE_POLICY' AND TRIM(content_text) = '';

UPDATE store_content SET content_text = '1. Thời hạn gửi yêu cầu\nKhách hàng có thể gửi yêu cầu trả hàng trong vòng 14 ngày sau khi đơn được hoàn tất. Yêu cầu được gửi từ trang chi tiết đơn hàng đã đăng nhập.\n\n2. Phạm vi trả hàng\nCó thể yêu cầu trả toàn bộ đơn hoặc chọn một phần sản phẩm và số lượng cần trả. Cửa hàng sẽ xem xét lý do, xác nhận hàng nhận lại và xử lý yêu cầu theo trạng thái hiển thị trên website.\n\n3. Hoàn tiền\nSố tiền hoàn được hệ thống tính theo giá trị sản phẩm tại thời điểm đặt và phần hàng được chấp nhận trả. Với COD, việc hoàn tiền thực tế được thực hiện ngoài hệ thống và chỉ được đánh dấu hoàn tất khi quản trị viên ghi nhận chứng từ. Với thanh toán mô phỏng, trạng thái hoàn cũng chỉ là mô phỏng, không có chuyển tiền thật.\n\n4. Cần hỗ trợ thêm?\nMở mục Hỗ trợ hoặc trang Liên hệ và cung cấp mã đơn để cửa hàng kiểm tra. Gửi yêu cầu không đồng nghĩa với việc đã được duyệt hoàn tiền.', updated_at = UTC_TIMESTAMP(6)
WHERE content_key = 'RETURN_POLICY' AND TRIM(content_text) = '';

UPDATE store_content SET content_text = '1. Phí vận chuyển\nHệ thống hiện áp dụng phí vận chuyển tiêu chuẩn cố định 30.000 ₫ cho đơn hàng local. Tổng tiền thanh toán được hiển thị và kiểm tra lại trước khi xác nhận đặt hàng.\n\n2. Theo dõi giao hàng\nKhách theo dõi trạng thái tại Đơn của tôi. Nhân viên có thể cập nhật đơn vị vận chuyển, mã vận đơn và các bước giao hàng; thông tin này hiển thị khi đã được ghi nhận.\n\n3. Thời gian giao dự kiến\nỨng dụng chưa tính thời gian giao tự động và không cam kết số ngày giao cố định. Nếu cần biết tình trạng đơn cụ thể, vui lòng gửi yêu cầu Hỗ trợ kèm mã đơn.\n\n4. Giao không thành công\nTrạng thái giao thất bại được ghi nhận riêng để cửa hàng kiểm tra và xử lý tiếp. Vui lòng bảo đảm tên, số điện thoại và địa chỉ nhận hàng chính xác khi đặt đơn.', updated_at = UTC_TIMESTAMP(6)
WHERE content_key = 'SHIPPING_POLICY' AND TRIM(content_text) = '';
