package vn.shop.order;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;
import com.fasterxml.jackson.databind.ObjectMapper;
import vn.shop.common.*;
import vn.shop.order.OrderDtos.*;
import java.util.*;
import java.util.concurrent.*;
import static org.mockito.Mockito.*;
import static org.mockito.ArgumentMatchers.*;
import static org.assertj.core.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class OrderIntegrationTest {
 @Autowired OrderService service;@Autowired OrderSaga saga;@Autowired OrderRepository orders;@Autowired CartRepository carts;@Autowired GuardRepository guards;@Autowired ObjectMapper mapper;@Autowired MockMvc mvc;@Autowired JwtService jwt;
 @Autowired FulfillmentService fulfillment;@Autowired FulfillmentRepository fulfillmentCommands;@MockitoBean PaymentBridge payment;@MockitoBean PromotionBridge promotion;
 @MockitoBean OrderRemote remote;@MockitoBean RemoteSessionVerifier verifier;
 @BeforeEach void setup()throws Exception{fulfillmentCommands.deleteAll();orders.deleteAll();carts.deleteAll();if(!guards.existsById(1L)){var g=new OrderGuard();g.id=1L;guards.save(g);}when(promotion.price(anyLong(),anyLong(),any())).thenAnswer(call->call.getArgument(2));when(payment.initialize(any())).thenReturn(mapper.createObjectNode().put("paymentState","UNPAID").put("shippingState","NEW"));when(payment.cancel(any())).thenReturn(mapper.createObjectNode().put("paymentState","CANCELLED").put("shippingState","CANCELLED"));when(verifier.valid(any())).thenReturn(true);when(remote.quote(anyLong())).thenReturn(mapper.readTree("{\"productId\":1,\"categoryId\":7,\"sku\":\"TEST-S\",\"productName\":\"Áo\",\"size\":\"S\",\"color\":\"Đen\",\"price\":100000,\"active\":true}"));when(remote.mutate(anyString(),anyString(),any())).thenReturn(mapper.readTree("{\"state\":\"HELD\"}"));}
 Checkout input(long rev){return new Checkout(rev,"Khách","0901234567","12 Hà Nội","");}
 OrderView create(){var c=service.setQuantity(1,1,2);return service.checkout(1,UUID.randomUUID().toString(),input(c.revision()));}
 @Test void emptyCartAndStaleRevisionRejected(){assertThatThrownBy(()->service.checkout(1,"empty-cart-key",input(0))).isInstanceOf(ApiException.class);service.setQuantity(1,1,2);assertThatThrownBy(()->service.checkout(1,"stale-cart-key",input(0))).isInstanceOf(ApiException.class);}
 @Test void cartIncludesCatalogImageWhenPresent()throws Exception{when(remote.quote(1)).thenReturn(mapper.readTree("{\"productId\":1,\"categoryId\":7,\"sku\":\"TEST-S\",\"productName\":\"Áo\",\"size\":\"S\",\"color\":\"Đen\",\"price\":100000,\"active\":true,\"imageUrl\":\"/api/catalog/images/demo.png\"}"));var cart=service.setQuantity(1,1,1);assertThat(cart.items().get(0).imageUrl()).isEqualTo("/api/catalog/images/demo.png");}
 @Test void snapshotTotalsAndSuccessfulSaga(){var o=create();assertThat(o.total()).isEqualByComparingTo("230000");assertThat(service.cartView(1).items()).isEmpty();saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).state()).isEqualTo("PLACED");saga.reconcile(o.id());verify(remote,times(1)).mutate(eq(o.id()),eq("/commit"),any());}
 @Test void checkoutKeepsCategoryWhenCatalogChangesLater()throws Exception{var o=create();assertThat(o.items().get(0).categoryId()).isEqualTo(7L);when(remote.quote(anyLong())).thenReturn(mapper.readTree("{\"productId\":1,\"categoryId\":9,\"sku\":\"TEST-S\",\"productName\":\"Áo\",\"size\":\"S\",\"color\":\"Đen\",\"price\":100000,\"active\":true}"));assertThat(service.get(o.id(),1,false).items().get(0).categoryId()).isEqualTo(7L);}
 @Test void parallelCheckoutCreatesOneOrder()throws Exception{var c=service.setQuantity(1,1,1);var pool=Executors.newFixedThreadPool(2);var gate=new CountDownLatch(1);Callable<OrderView> call=()->{gate.await();return service.checkout(1,"same-order-key",input(c.revision()));};try{var a=pool.submit(call);var b=pool.submit(call);gate.countDown();assertThat(a.get(10,TimeUnit.SECONDS).id()).isEqualTo(b.get(10,TimeUnit.SECONDS).id());assertThat(orders.count()).isEqualTo(1);}finally{pool.shutdownNow();}}
 @Test void keyPayloadMismatchRejected(){var c=service.setQuantity(1,1,1);service.checkout(1,"same-order-key",input(c.revision()));assertThatThrownBy(()->service.checkout(1,"same-order-key",input(99))).isInstanceOf(ApiException.class);}
 @Test void ambiguousCommitRetriesWithoutPrematureFailure(){var o=create();when(remote.mutate(eq(o.id()),eq("/commit"),any())).thenThrow(new ApiException(503,"timeout"));saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).state()).isEqualTo("PROCESSING");when(remote.mutate(eq(o.id()),eq("/commit"),any())).thenReturn(mapper.createObjectNode().put("state","COMMITTED"));saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).state()).isEqualTo("PLACED");}
 @Test void stockConflictCompensatesThenFails(){var o=create();when(remote.mutate(eq(o.id()),eq(""),any())).thenThrow(new ApiException(409,"out of stock"));saga.reconcile(o.id());when(remote.reservation(o.id())).thenThrow(ApiException.missing());saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).state()).isEqualTo("FAILED");}
 @Test void cancellationRestocksExactlyOnce(){var o=create();saga.reconcile(o.id());service.transition(o.id(),1,false,"CANCELLED");when(remote.reservation(o.id())).thenReturn(mapper.createObjectNode().put("state","COMMITTED"));saga.reconcile(o.id());saga.reconcile(o.id());service.transition(o.id(),1,false,"CANCELLED");verify(remote,times(1)).mutate(eq(o.id()),eq("/restock"),any());assertThat(service.get(o.id(),1,false).state()).isEqualTo("CANCELLED");assertThatThrownBy(()->service.transition(o.id(),2,true,"CONFIRMED")).isInstanceOf(ApiException.class);}
 @Test void ownerAndRoleEnforcedAtHttpBoundary()throws Exception{var o=create();String token=jwt.issue(2,"test",List.of("CUSTOMER"),false);mvc.perform(get("/api/orders/"+o.id()).header("Authorization","Bearer "+token)).andExpect(status().isNotFound());mvc.perform(get("/api/orders/manage").header("Authorization","Bearer "+token)).andExpect(status().isForbidden());mvc.perform(get("/api/cart")).andExpect(status().isUnauthorized());}
 @Test void staffCannotSkipStates(){var o=create();saga.reconcile(o.id());assertThatThrownBy(()->service.transition(o.id(),2,true,"PACKING")).isInstanceOf(ApiException.class);service.transition(o.id(),2,true,"CONFIRMED");service.transition(o.id(),2,true,"PACKING");assertThatThrownBy(()->service.transition(o.id(),1,false,"CANCELLED")).isInstanceOf(ApiException.class);}
 @Test void cancellationTimeoutStaysPendingUntilConfirmed(){var o=create();service.transition(o.id(),1,false,"CANCELLED");when(remote.reservation(o.id())).thenReturn(mapper.createObjectNode().put("state","HELD"));when(remote.mutate(eq(o.id()),eq("/release"),any())).thenThrow(new ApiException(503,"timeout"));saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).state()).isEqualTo("CANCEL_PENDING");when(remote.reservation(o.id())).thenReturn(mapper.createObjectNode().put("state","RELEASED"));saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).state()).isEqualTo("CANCELLED");}
 @Test void abandonedProcessingMovesToCompensation(){var o=create();var entity=orders.findById(o.id()).orElseThrow();entity.createdAt=java.time.Instant.now().minusSeconds(601);orders.save(entity);saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).state()).isEqualTo("FAIL_PENDING");verify(remote,never()).mutate(anyString(),anyString(),any());}
 @Test void cartsAreIsolatedAndStoppedProductsCannotBePurchased(){service.setQuantity(1,1,2);assertThat(service.cartView(2).items()).isEmpty();service.remove(2,1L);assertThat(service.cartView(1).items()).hasSize(1);when(remote.quote(1)).thenReturn(mapper.createObjectNode().put("active",false));assertThatThrownBy(()->service.checkout(1,"inactive-item-key",input(1))).isInstanceOf(ApiException.class);assertThat(orders.count()).isZero();}
 FulfillmentInput action(String action){return new FulfillmentInput(action,"Local","TRACK-001","Nhân viên","COD-001",new java.math.BigDecimal("25000"),"Kiểm thử");}
 OrderView simulated(){var c=service.setQuantity(1,1,1);var o=service.checkout(1,UUID.randomUUID().toString(),new Checkout(c.revision(),"Khách","0901234567","Hà Nội","","SIMULATED"));saga.reconcile(o.id());return service.get(o.id(),1,false);}
 @Test void simulatedPaymentPersistsPendingThenSuccessfulProjection(){var o=simulated();assertThat(o.state()).isEqualTo("AWAITING_PAYMENT");var c=fulfillment.submit(o.id(),1,false,"simulation-key",action("SIM_SUCCESS"));assertThat(fulfillment.submit(o.id(),1,false,"simulation-key",action("SIM_SUCCESS")).id()).isEqualTo(c.id());when(payment.execute(any(),eq(c.id()),eq(1L),any())).thenReturn(mapper.createObjectNode().put("paymentState","SIMULATED_PAID").put("shippingState","NEW"));saga.reconcile(o.id());var result=service.get(o.id(),1,false);assertThat(result.state()).isEqualTo("PLACED");assertThat(result.paymentState()).isEqualTo("SIMULATED_PAID");assertThat(result.pendingCommandId()).isNull();}
 @Test void uncertainShippingBlocksCancellationAndRetriesSameCommand(){var o=create();saga.reconcile(o.id());service.transition(o.id(),2,true,"CONFIRMED");service.transition(o.id(),2,true,"PACKING");var c=fulfillment.submit(o.id(),2,true,"ship-command-key",action("SHIP"));when(payment.execute(any(),eq(c.id()),eq(2L),any())).thenThrow(new ApiException(503,"timeout"));saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).pendingCommandId()).isEqualTo(c.id());assertThatThrownBy(()->service.transition(o.id(),2,true,"CANCELLED")).isInstanceOf(ApiException.class);when(payment.execute(any(),eq(c.id()),eq(2L),any())).thenReturn(mapper.createObjectNode().put("paymentState","UNPAID").put("shippingState","SHIPPING"));saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).state()).isEqualTo("SHIPPED");verify(payment,times(2)).execute(any(),eq(c.id()),eq(2L),any());}
 @Test void rejectedCommandCanBeCorrectedWithNewKey(){var o=simulated();var c=fulfillment.submit(o.id(),1,false,"rejected-command",action("SIM_SUCCESS"));when(payment.execute(any(),anyString(),anyLong(),any())).thenThrow(new ApiException(409,"Không hợp lệ"));saga.reconcile(o.id());assertThat(fulfillment.list(o.id(),1,false).get(0).state()).isEqualTo("REJECTED");assertThat(service.get(o.id(),1,false).pendingCommandId()).isNull();assertThat(fulfillment.submit(o.id(),1,false,"corrected-command",action("SIM_FAILURE")).state()).isEqualTo("PENDING");}
 @Test void simulationExpiresAndCannotBePaidAfterDeadline(){var o=simulated();var row=orders.findById(o.id()).orElseThrow();row.createdAt=java.time.Instant.now().minusSeconds(901);orders.save(row);assertThatThrownBy(()->fulfillment.submit(o.id(),1,false,"late-simulation-key",action("SIM_SUCCESS"))).isInstanceOf(ApiException.class);saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).state()).isEqualTo("FAIL_PENDING");}
 @Test void paymentOutageKeepsOrderProcessingWithoutInventoryCommit(){var o=create();when(promotion.price(anyLong(),anyLong(),any())).thenAnswer(call->call.getArgument(2));when(payment.initialize(any())).thenThrow(new ApiException(503,"offline"));saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).state()).isEqualTo("PROCESSING");verify(remote,never()).mutate(eq(o.id()),eq("/commit"),any());}
 @Test void fulfillmentHttpRequiresStaffForShippingAndOwnerForSimulation()throws Exception{var o=simulated();String outsider=jwt.issue(2,"test",List.of("CUSTOMER"),false),owner=jwt.issue(1,"test",List.of("CUSTOMER"),false);mvc.perform(post("/api/orders/"+o.id()+"/fulfillment").header("Authorization","Bearer "+outsider).header("Idempotency-Key","wrong-owner-key").contentType("application/json").content(mapper.writeValueAsString(action("SIM_SUCCESS")))).andExpect(status().isNotFound());mvc.perform(post("/api/orders/"+o.id()+"/fulfillment").header("Authorization","Bearer "+owner).header("Idempotency-Key","wrong-role-key").contentType("application/json").content(mapper.writeValueAsString(action("SHIP")))).andExpect(status().isForbidden());}
 @Test void couponDiscountSnapshottedAndCommittedOnce(){var c=service.setQuantity(1,1,2);when(promotion.quote(eq("TENOFF"),any(),eq(1L))).thenReturn(mapper.createObjectNode().put("code","TENOFF").put("discount",15000));when(promotion.reserve(any())).thenReturn(mapper.createObjectNode().put("discount",15000));var o=service.checkout(1,"discount-key",new Checkout(c.revision(),"Khách","0901234567","Hà Nội","","COD","TENOFF"));assertThat(o.total()).isEqualByComparingTo("215000");assertThat(o.discount()).isEqualByComparingTo("15000");saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).state()).isEqualTo("PLACED");verify(promotion,times(1)).commit(any());service.transition(o.id(),1,false,"CANCELLED");when(remote.reservation(o.id())).thenReturn(mapper.createObjectNode().put("state","COMMITTED"));saga.reconcile(o.id());saga.reconcile(o.id());verify(promotion,times(1)).release(any());}
 @Test void couponReservationConflictNeverReservesStock(){var c=service.setQuantity(1,1,1);when(promotion.quote(eq("TENOFF"),any(),eq(1L))).thenReturn(mapper.createObjectNode().put("code","TENOFF").put("discount",10000));var o=service.checkout(1,"coupon-conflict-key",new Checkout(c.revision(),"Khách","0901234567","Hà Nội","","COD","TENOFF"));when(promotion.reserve(any())).thenThrow(new ApiException(409,"Mã hết lượt"));saga.reconcile(o.id());assertThat(service.get(o.id(),1,false).state()).isEqualTo("FAIL_PENDING");verify(remote,never()).mutate(eq(o.id()),eq(""),any());}
 @Test void productPromotionChangesItemSnapshot(){when(promotion.price(anyLong(),anyLong(),any())).thenAnswer(call->((java.math.BigDecimal)call.getArgument(2)).subtract(new java.math.BigDecimal("10000")));var c=service.setQuantity(1,1,2);var o=service.checkout(1,"product-offer-key",input(c.revision()));assertThat(o.items().get(0).unitPrice()).isEqualByComparingTo("90000");assertThat(o.subtotal()).isEqualByComparingTo("180000");assertThat(o.total()).isEqualByComparingTo("210000");}
 @Test void staffSearchesOrdersByCodeRecipientPhoneAndLocalDate(){
  var firstCart=service.setQuantity(1,1,1);
  var first=service.checkout(1,"manager-search-1",new Checkout(firstCart.revision(),"Minh Anh","0901111222","Hà Nội",""));
  var secondCart=service.setQuantity(2,1,1);
  var second=service.checkout(2,"manager-search-2",new Checkout(secondCart.revision(),"Lan Phương","0903333444","Đà Nẵng",""));
  var yesterday=java.time.LocalDate.now(java.time.ZoneId.of("Asia/Ho_Chi_Minh")).minusDays(1);
  var older=orders.findById(second.id()).orElseThrow();older.createdAt=yesterday.atTime(12,0).atZone(java.time.ZoneId.of("Asia/Ho_Chi_Minh")).toInstant();orders.saveAndFlush(older);
  assertThat(service.list(5,true,null,"Minh Anh",null,null,0).content()).extracting(OrderView::id).containsExactly(first.id());
  assertThat(service.list(5,true,null,"0903333",null,null,0).content()).extracting(OrderView::id).containsExactly(second.id());
  assertThat(service.list(5,true,null,first.id().substring(0,8),null,null,0).content()).extracting(OrderView::id).containsExactly(first.id());
  assertThat(service.list(5,true,null,null,yesterday,yesterday,0).content()).extracting(OrderView::id).containsExactly(second.id());
  assertThatThrownBy(()->service.list(5,true,null,null,yesterday.plusDays(1),yesterday,0)).isInstanceOf(ApiException.class);
  assertThat(service.list(1,false,null,0).content()).extracting(OrderView::id).containsExactly(first.id());
 }
}



