import React, { useEffect, useState } from 'react';
import { api, errorMessage, money } from './api';
export const paymentNames = { UNPAID: 'Chưa thanh toán', PAID: 'Đã xác nhận thanh toán', REFUND_PENDING: 'Chờ hoàn tiền thực tế', REFUNDED: 'Đã ghi nhận hoàn tiền thực tế', SIMULATED_PAID: 'Mô phỏng thành công — không thu tiền thật', SIMULATED_FAILED: 'Mô phỏng thất bại', SIMULATED_REFUNDED: 'Đã hoàn mô phỏng — không chuyển tiền thật', CANCELLED: 'Đã hủy thanh toán' };
const shippingNames = { NEW: 'Chưa bàn giao', SHIPPING: 'Đang vận chuyển', DELIVERED: 'Giao thành công', DELIVERY_FAILED: 'Giao thất bại', RETURNED: 'Đã nhận hàng hoàn', CANCELLED: 'Đã hủy giao hàng' };
const actionNames = { INIT: 'Khởi tạo', SIM_SUCCESS: 'Mô phỏng thành công', SIM_FAILURE: 'Mô phỏng thất bại', BANK_CONFIRM: 'Xác nhận đã nhận chuyển khoản', SHIP: 'Bàn giao vận chuyển', DELIVER: 'Xác nhận giao thành công', DELIVERY_FAIL: 'Ghi nhận giao thất bại', RETRY_SHIP: 'Giao lại', RETURN_RECEIVED: 'Xác nhận đã nhận hàng hoàn', COLLECT_COD: 'Xác nhận đã thu đủ COD', CANCEL: 'Hủy thanh toán / vận chuyển' };
export default function FulfillmentPanel({ order, manage, admin = false, canSimulate, onUpdated }) {
 const [data, setData] = useState(null), [commands, setCommands] = useState([]), [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false), [attempt, setAttempt] = useState(null);
 const [form, setForm] = useState({ carrier: '', tracking: '', assignee: '', carrierCost: '30000', reference: '', note: '' });
 useEffect(() => {
  let active = true;
  Promise.all([api.get(`/payments/${order.id}`).catch(e => { if (e.response?.status === 404) return { data: null }; throw e; }), api.get(`/orders/${order.id}/fulfillment`)])
   .then(([p, c]) => { if (active) { setData(p.data); setCommands(c.data); setError(''); } }).catch(e => { if (active) setError(errorMessage(e)); });
  return () => { active = false; };
 }, [order.id, order.state, order.paymentState, order.shippingState, order.pendingCommandId, message]);
 const send = async request => {
  setBusy(true); setError(''); setMessage(''); setAttempt(request);
  try { const res = await api.post(`/orders/${order.id}/fulfillment`, request.body, { headers: { 'Idempotency-Key': request.key } }); setAttempt(null); setMessage(res.data.state === 'REJECTED' ? `Yêu cầu bị từ chối: ${res.data.failure}` : 'Đã ghi nhận yêu cầu. Kết quả sẽ cập nhật sau khi dịch vụ xác nhận.'); await onUpdated(); }
  catch (e) { setError(errorMessage(e)); if (e.response && e.response.status >= 400 && e.response.status < 500) setAttempt(null); }
  finally { setBusy(false); }
 };
 const submit = action => {
  if (!window.confirm(`${actionNames[action]}?${action === 'COLLECT_COD' || action === 'BANK_CONFIRM' ? ` Chỉ xác nhận sau khi thực tế đã nhận đủ ${money(order.total)} và đối chiếu mã giao dịch.` : ''}`)) return;
  send({ key: crypto.randomUUID(), body: { action, ...form, carrierCost: form.carrierCost === '' ? null : Number(form.carrierCost) } });
 };
 const disabled = busy || !!attempt || !!order.pendingCommandId;
 const change = e => setForm({ ...form, [e.target.name]: e.target.value });
 const field = (name, label, options = {}) => <div className="mb-3" key={name}><label className="form-label" htmlFor={`fulfillment-${name}`}>{label}</label><input className="form-control" id={`fulfillment-${name}`} name={name} value={form[name]} onChange={change} maxLength={name === 'note' ? 500 : name === 'reference' ? 190 : 120} {...options}/></div>;
 return <section className="border-top mt-4 pt-4"><h3>Thanh toán và vận chuyển</h3>
  <p>{order.paymentMethod === 'SIMULATED' ? 'Thanh toán mô phỏng local' : order.paymentMethod === 'BANK_TRANSFER' ? 'Chuyển khoản ngân hàng' : 'Thanh toán khi nhận hàng (COD)'} · {paymentNames[order.paymentState] || order.paymentState}</p>
  {order.paymentMethod === 'BANK_TRANSFER' && data?.bankAccountNumber && <div className="alert alert-info"><strong>{order.paymentState === 'PAID' ? 'Đã đối soát chuyển khoản' : 'Thông tin chuyển khoản cho đơn này'}</strong><p className="mb-1 mt-2">Ngân hàng: {data.bankName}<br/>Chủ tài khoản: {data.bankAccountName}<br/>Số tài khoản: <strong>{data.bankAccountNumber}</strong><br/>Số tiền: <strong>{money(order.total)}</strong><br/>Nội dung chuyển khoản: <strong>LUA{order.id.replaceAll('-', '').toUpperCase()}</strong></p>{order.paymentState !== 'PAID' && <small>Việc chuyển tiền không tự đánh dấu đơn đã thanh toán. Cửa hàng sẽ kiểm tra sao kê và xác nhận.</small>}</div>}
  {order.paymentMethod === 'SIMULATED' && <p className="alert alert-warning">Đây là giao dịch thử nghiệm trong database local, không kết nối ngân hàng và không thu hoặc hoàn tiền thật.</p>}
  {error && <p role="alert" className="alert alert-danger">{error}</p>}{message && <p role="status" className="alert alert-info">{message}</p>}
  {order.pendingCommandId && <p role="status">Đang đối soát thao tác. Vui lòng chờ trước khi thay đổi đơn hàng.</p>}
  {attempt && <button className="btn btn-warning mb-3" disabled={busy} onClick={() => send(attempt)}>Kiểm tra lại thao tác chưa rõ kết quả</button>}
  {data ? <><p>Vận chuyển: <strong>{shippingNames[data.shippingState]}</strong></p>{data.tracking && <p>Đơn vị: {data.carrier} · Mã vận đơn: {data.tracking}</p>}{manage && data.assignee && <p>Phụ trách: {data.assignee} · Chi phí trả đơn vị vận chuyển: {money(data.carrierCost)}</p>}{data.reference && <p>Mã chứng từ / tham chiếu: {data.reference}</p>}{data.refunds.map((r, i) => <p key={i}>{r.state === 'PENDING_MANUAL' ? 'Chờ hoàn COD' : r.state === 'REFUNDED' ? 'Đã hoàn COD' : 'Hoàn mô phỏng'} {money(r.amount)} — {r.reason}</p>)}</> : <p className="text-muted">Chưa có hồ sơ thanh toán/vận chuyển. Hồ sơ được tạo khi xử lý đơn hoặc thao tác hợp lệ tiếp theo.</p>}
  {canSimulate && order.state === 'AWAITING_PAYMENT' && <div className="d-flex flex-wrap gap-3 mb-3"><button className="btn btn-primary" disabled={disabled} onClick={() => submit('SIM_SUCCESS')}>Mô phỏng thanh toán thành công</button><button className="btn btn-outline-danger" disabled={disabled} onClick={() => submit('SIM_FAILURE')}>Mô phỏng thanh toán thất bại</button><p>Hạn thao tác: 15 phút kể từ lúc tạo đơn. Quá hạn hệ thống sẽ xử lý hủy và hoàn kho.</p></div>}
  {admin && order.paymentMethod === 'BANK_TRANSFER' && order.state === 'AWAITING_BANK' && <form onSubmit={e => { e.preventDefault(); submit('BANK_CONFIRM'); }}><fieldset disabled={disabled}>{field('reference', 'Mã giao dịch ngân hàng thực tế', { required: true })}<p>Đối chiếu đủ {money(order.total)} và đúng nội dung chuyển khoản trong sao kê trước khi xác nhận. Mỗi mã giao dịch chỉ dùng cho một đơn.</p><button className="btn btn-primary">Xác nhận đã nhận chuyển khoản</button></fieldset></form>}
  {manage && order.state === 'PACKING' && <form onSubmit={e => { e.preventDefault(); submit('SHIP'); }}><fieldset disabled={disabled}>{field('carrier', 'Đơn vị vận chuyển', { required: true })}{field('tracking', 'Mã vận đơn', { required: true })}{field('assignee', 'Người phụ trách giao hàng', { required: true })}{field('carrierCost', 'Chi phí trả đơn vị vận chuyển (VNĐ)', { type: 'number', min: 0, step: '0.01', required: true })}<p>Chi phí này được ghi riêng; không thay đổi phí đã báo cho khách trong đơn.</p><button className="btn btn-primary">Bàn giao vận chuyển</button></fieldset></form>}
  {manage && order.state === 'SHIPPED' && <><button className="btn btn-primary mb-3" disabled={disabled} onClick={() => submit('DELIVER')}>Xác nhận giao thành công</button><form onSubmit={e => { e.preventDefault(); submit('DELIVERY_FAIL'); }}><fieldset disabled={disabled}>{field('note', 'Lý do giao thất bại', { required: true })}<button className="btn btn-outline-danger">Ghi nhận giao thất bại</button></fieldset></form></>}
  {manage && order.state === 'DELIVERY_FAILED' && <><button className="btn btn-primary mb-3" disabled={disabled} onClick={() => submit('RETRY_SHIP')}>Giao lại</button><form onSubmit={e => { e.preventDefault(); submit('RETURN_RECEIVED'); }}><fieldset disabled={disabled}>{field('note', 'Ghi chú nhận hàng hoàn', { required: true })}<button className="btn btn-outline-danger">Xác nhận đã nhận hàng hoàn</button></fieldset></form></>}
  {manage && order.state === 'DELIVERED' && order.paymentMethod === 'COD' && <form onSubmit={e => { e.preventDefault(); submit('COLLECT_COD'); }}><fieldset disabled={disabled}>{field('reference', 'Mã chứng từ thu COD', { required: true })}<p>Cần thu đủ {money(order.total)}. Thao tác này ghi nhận thu tiền thủ công, không tự thu qua ngân hàng.</p><button className="btn btn-primary">Xác nhận đã thu đủ COD</button></fieldset></form>}
  {commands.length > 0 && <div className="mt-4"><h4>Yêu cầu xử lý gần đây</h4><ul>{commands.map(c => <li key={c.id}>{actionNames[c.action] || c.action}: {c.state === 'PENDING' ? 'Đang đối soát' : c.state === 'DONE' ? 'Đã xử lý' : `Bị từ chối — ${c.failure}`}</li>)}</ul></div>}
  {data?.history.length > 0 && <details className="mt-3"><summary>Lịch sử thanh toán và vận chuyển</summary><ul>{data.history.map((h, i) => <li key={i}>{new Date(h.createdAt).toLocaleString('vi-VN')} · {actionNames[h.action] || h.action}{h.note ? ` — ${h.note}` : ''}</li>)}</ul></details>}
 </section>;
}
