import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, errorMessage, money } from './api';

const localDate = day => { const d = new Date(day); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 10); };
const initialRange = () => ({ from: localDate(new Date(new Date().getFullYear(), new Date().getMonth(), 1)), to: localDate(new Date()), group: 'DAY' });
function ErrorNotice({ error }) { return error ? <p role="alert" className="alert alert-danger">{error}</p> : null; }

export function DashboardPage() {
 const [data, setData] = useState(null), [error, setError] = useState('');
 const load = () => { setError(''); api.get('/reports/dashboard').then(r => setData(r.data)).catch(e => setError(errorMessage(e))); };
 useEffect(load, []);
 return <><h1>Tổng quan cửa hàng</h1><ErrorNotice error={error}/>{!data && !error && <p role="status">Đang tải số liệu từ các service…</p>}{data && <><div className="row g-3 mb-4">{[['Doanh thu COD đã thu', data.realizedRevenue, true], ['Hôm nay', data.todayRevenue, true], ['Tuần này', data.weekRevenue, true], ['Tháng này', data.monthRevenue, true], ['Năm nay', data.yearRevenue, true], ['Đơn hoàn tất', data.completedOrders], ['Chờ xử lý', data.pendingOrders], ['Đang giao', data.shippingOrders], ['Đã hủy', data.cancelledOrders], ['Sản phẩm', data.productCount], ['Khách hàng', data.customerCount], ['Biến thể sắp hết', data.lowStockCount]].map(([label, value, currency]) => <div key={label} className="col-6 col-lg-3"><div className="panel h-100"><p className="text-muted mb-2">{label}</p><strong className="fs-4">{currency ? money(value) : value}</strong></div></div>)}</div><p className="alert alert-info">Giao dịch mô phỏng local: {money(data.simulatedTurnover)} — không tính vào doanh thu COD đã thu.</p><div className="row g-4"><section className="col-lg-6"><div className="panel h-100"><h2>Sản phẩm bán chạy</h2>{data.bestSellers.length === 0 && <p>Chưa có đơn COD hoàn tất.</p>}{data.bestSellers.map(p => <p key={p.productId}><Link to={`/products/${p.productId}`}>{p.productName}</Link> · {p.quantity} sản phẩm · {money(p.revenue)}</p>)}</div></section><section className="col-lg-6"><div className="panel h-100"><h2>Đơn gần đây</h2>{data.recentOrders.length === 0 && <p>Chưa có đơn hàng.</p>}{data.recentOrders.map(o => <p key={o.id}><Link to={`/orders/${o.id}`}>{o.id.slice(0, 8)}</Link> · {o.state} · {money(o.total)}</p>)}</div></section></div><p className="mt-4"><Link className="btn btn-primary" to="/admin/reports">Xem báo cáo theo thời gian</Link></p></>}</>;
}

export function RevenuePage() {
 const [range, setRange] = useState(initialRange), [data, setData] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
 const load = async next => { setBusy(true); setError(''); try { setData((await api.get('/reports/revenue', { params: next })).data); } catch (e) { setData(null); setError(errorMessage(e)); } finally { setBusy(false); } };
 useEffect(() => { load(range); }, []);
 const download = async () => { setBusy(true); setError(''); try { const r = await api.get('/reports/revenue.csv', { params: range, responseType: 'blob' }); const url = URL.createObjectURL(r.data); const a = document.createElement('a'); a.href = url; a.download = 'doanh-thu.csv'; document.body.append(a); a.click(); a.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
 const peak = Math.max(1, ...(data?.buckets || []).map(b => Number(b.realizedRevenue)));
 return <><h1>Báo cáo doanh thu</h1><p className="d-flex gap-3 flex-wrap"><Link to="/admin/order-exceptions">Xem báo cáo đơn hủy và hoàn trả →</Link><Link to="/admin/category-revenue">Xem doanh thu theo danh mục →</Link></p><p>Chỉ đơn COD đã hoàn tất và đã ghi nhận thu tiền được tính là doanh thu. Giá trị mô phỏng hiển thị riêng.</p><ErrorNotice error={error}/><form className="panel mb-4" onSubmit={e => { e.preventDefault(); load(range); }}><div className="row g-3"><div className="col-md-4"><label className="form-label" htmlFor="report-from">Từ ngày</label><input className="form-control" id="report-from" type="date" required value={range.from} onChange={e => setRange({ ...range, from: e.target.value })}/></div><div className="col-md-4"><label className="form-label" htmlFor="report-to">Đến ngày</label><input className="form-control" id="report-to" type="date" required value={range.to} onChange={e => setRange({ ...range, to: e.target.value })}/></div><div className="col-md-4"><label className="form-label" htmlFor="report-group">Nhóm theo</label><select className="form-select" id="report-group" value={range.group} onChange={e => setRange({ ...range, group: e.target.value })}><option value="DAY">Ngày</option><option value="MONTH">Tháng</option><option value="QUARTER">Quý</option><option value="YEAR">Năm</option></select></div></div><div className="d-flex gap-2 mt-3"><button className="btn btn-primary" disabled={busy}>Xem báo cáo</button><button className="btn btn-outline-dark" type="button" disabled={busy || !data} onClick={download}>Xuất CSV</button></div></form>{busy && <p role="status">Đang tổng hợp dữ liệu…</p>}{data && <section className="panel"><h2>Doanh thu COD: {money(data.realizedRevenue)}</h2><p>Giao dịch mô phỏng: {money(data.simulatedTurnover)} · {data.completedOrders} đơn hoàn tất trong kỳ</p>{data.buckets.length === 0 && <p>Không có đơn hoàn tất trong khoảng đã chọn.</p>}{data.buckets.map(b => <div className="mb-3" key={b.period}><div className="d-flex justify-content-between"><strong>{b.period}</strong><span>{money(b.realizedRevenue)} · {b.completedOrders} đơn</span></div><div className="progress" role="img" aria-label={`${b.period}: ${money(b.realizedRevenue)}`}><div className="progress-bar" style={{ width: `${Number(b.realizedRevenue) > 0 ? Math.max(1, Number(b.realizedRevenue) / peak * 100) : 0}%` }}/></div>{Number(b.simulatedTurnover) > 0 && <small>Mô phỏng: {money(b.simulatedTurnover)}</small>}</div>)}</section>}</>;
}

export function NotificationsPage() {
 const [data, setData] = useState(null), [page, setPage] = useState(0), [error, setError] = useState(''), [busy, setBusy] = useState(false);
 const load = async p => { setError(''); try { setData((await api.get('/notifications', { params: { page: p } })).data); } catch (e) { setError(errorMessage(e)); } };
 useEffect(() => { load(page); }, [page]);
 const markRead = async id => { setBusy(true); setError(''); try { await api.put(`/notifications/${id}/read`); await load(page); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
 return <><h1>Thông báo của tôi</h1><ErrorNotice error={error}/>{!data && !error && <p role="status">Đang đồng bộ thông báo…</p>}{data && <section className="panel">{data.content.length === 0 && <p>Chưa có thông báo.</p>}{data.content.map(n => <article className={`border-bottom py-3 ${n.readAt ? '' : 'fw-semibold'}`} key={n.id}><p className="mb-1">{n.title} · {new Date(n.createdAt).toLocaleString('vi-VN')}</p><p>{n.body}</p>{n.linkPath ? <Link to={n.linkPath}>Xem ưu đãi</Link> : <Link to={`/orders/${n.orderId}`}>Xem đơn hàng</Link>}{!n.readAt && <button className="btn btn-outline-dark btn-sm ms-3" disabled={busy} onClick={() => markRead(n.id)}>Đánh dấu đã đọc</button>}</article>)}<div className="d-flex gap-2 mt-3"><button className="btn btn-outline-dark" disabled={page === 0} onClick={() => setPage(page - 1)}>Trước</button><span>Trang {page + 1}</span><button className="btn btn-outline-dark" disabled={data.last} onClick={() => setPage(page + 1)}>Sau</button></div></section>}</>;
}


