ALTER TABLE orders DROP CHECK chk_order_state;
ALTER TABLE orders ADD CONSTRAINT chk_order_state CHECK(state IN ('PROCESSING','AWAITING_PAYMENT','AWAITING_BANK','PLACED','CONFIRMED','PACKING','SHIPPED','DELIVERED','DELIVERY_FAILED','COMPLETED','RETURNED','CANCEL_PENDING','CANCELLED','FAIL_PENDING','FAILED'));
