import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, errorMessage, money } from './api';
const dateInput = value => { const d = value ? new Date(value) : new Date(); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };
const blankCoupon = () => ({ code: '', type: 'PERCENT', value: 10, minimumTotal: 0, maximumDiscount: '', totalLimit: 100, perCustomerLimit: 1, startsAt: dateInput(), endsAt: dateInput(new Date(Date.now() + 30 * 86400000)), active: true });
const blankPromotion = () => ({ name: '', targetType: 'PRODUCT', targetId: '', type: 'PERCENT', value: 10, maximumDiscount: '', startsAt: dateInput(), endsAt: dateInput(new Date(Date.now() + 30 * 86400000)), active: true });
const inputTime = form => ({ ...form, value: Number(form.value), maximumDiscount: form.maximumDiscount === '' ? null : Number(form.maximumDiscount), startsAt: new Date(form.startsAt).toISOString(), endsAt: new Date(form.endsAt).toISOString() });
function Notice({ error, message }) { return <>{error && <p role="alert" className="alert alert-danger">{error}</p>}{message && <p role="status" className="alert alert-success">{message}</p>}</>; }
function DateFields({ form, setForm }) { return <div className="row g-3"><div className="col-md-6"><label className="form-label" htmlFor="promotion-start">Bắt đầu</label><input className="form-control" id="promotion-start" type="datetime-local" required value={form.startsAt} onChange={e => setForm({ ...form, startsAt: e.target.value })}/></div><div className="col-md-6"><label className="form-label" htmlFor="promotion-end">Kết thúc</label><input className="form-control" id="promotion-end" type="datetime-local" required value={form.endsAt} onChange={e => setForm({ ...form, endsAt: e.target.value })}/></div></div>; }
function ValueFields({ form, setForm }) { return <div className="row g-3 my-2"><div className="col-md-4"><label className="form-label" htmlFor="discount-type">Cách giảm</label><select className="form-select" id="discount-type" value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option value="PERCENT">Phần trăm</option><option value="FIXED">Số tiền VNĐ</option></select></div><div className="col-md-4"><label className="form-label" htmlFor="discount-value">Giá trị giảm</label><input className="form-control" id="discount-value" type="number" step="0.01" min="0.01" max={form.type === 'PERCENT' ? 100 : undefined} required value={form.value} onChange={e => setForm({ ...form, value: e.target.value })}/></div><div className="col-md-4"><label className="form-label" htmlFor="discount-cap">Giảm tối đa (để trống nếu không giới hạn)</label><input className="form-control" id="discount-cap" type="number" step="0.01" min="0" value={form.maximumDiscount ?? ''} onChange={e => setForm({ ...form, maximumDiscount: e.target.value })}/></div></div>; }
export function CouponManager() {
 const [rows, setRows] = useState(null), [form, setForm] = useState(blankCoupon), [editing, setEditing] = useState(null), [page, setPage] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('');
 const load = async () => setRows((await api.get('/coupons/manage', { params: { page } })).data);
 useEffect(() => { load().catch(e => setError(errorMessage(e))); }, [page]);
 const edit = c => { setEditing(c.id); setForm({ ...c, startsAt: dateInput(c.startsAt), endsAt: dateInput(c.endsAt), maximumDiscount: c.maximumDiscount ?? '' }); };
 const save = async e => { e.preventDefault(); setBusy(true); setError(''); setMessage(''); try { const body = { ...inputTime(form), code: form.code.toUpperCase().trim(), minimumTotal: Number(form.minimumTotal), totalLimit: Number(form.totalLimit), perCustomerLimit: Number(form.perCustomerLimit) }; if (editing) await api.put(`/coupons/manage/${editing}`, body); else await api.post('/coupons/manage', body); setEditing(null); setForm(blankCoupon()); setMessage('Đã lưu mã giảm giá vào database.'); await load(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
 return <><h1>Quản lý mã giảm giá</h1><Notice error={error} message={message}/><form className="panel mb-4" onSubmit={save}><h2>{editing ? 'Chỉnh sửa mã' : 'Thêm mã giảm giá'}</h2><label className="form-label" htmlFor="coupon-code">Mã (4–40 ký tự A-Z, số, _ hoặc -)</label><input className="form-control" id="coupon-code" required minLength={4} maxLength={40} pattern="[A-Za-z0-9_-]{4,40}" value={form.code} onChange={e => setForm({ ...form, code: e.target.value })}/><ValueFields form={form} setForm={setForm}/><div className="row g-3 mb-3">{[['minimumTotal', 'Đơn hàng tối thiểu'], ['totalLimit', 'Tổng lượt dùng'], ['perCustomerLimit', 'Lượt mỗi khách']].map(([key, label]) => <div className="col-md-4" key={key}><label className="form-label" htmlFor={`coupon-${key}`}>{label}</label><input className="form-control" id={`coupon-${key}`} type="number" min={key === 'minimumTotal' ? 0 : 1} step={key === 'minimumTotal' ? '0.01' : 1} required value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })}/></div>)}</div><DateFields form={form} setForm={setForm}/><label className="d-block my-3"><input type="checkbox" className="me-2" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })}/>Đang sử dụng</label><button className="btn btn-primary" disabled={busy}>{busy ? 'Đang lưu…' : 'Lưu mã'}</button>{editing && <button type="button" className="btn btn-link" onClick={() => { setEditing(null); setForm(blankCoupon()); }}>Hủy sửa</button>}</form><section className="panel"><h2>Danh sách mã</h2>{rows ? <><div className="table-responsive"><table className="table"><thead><tr><th>Mã</th><th>Giảm</th><th>Lượt đã giữ/dùng</th><th>Hiệu lực</th><th>Thao tác</th></tr></thead><tbody>{rows.content.map(c => <tr key={c.id}><td>{c.code}</td><td>{c.type === 'PERCENT' ? `${c.value}%` : money(c.value)}</td><td>{c.heldOrUsed}/{c.totalLimit}</td><td>{c.active ? 'Đang bật' : 'Đã tắt'} · {new Date(c.endsAt).toLocaleDateString('vi-VN')}</td><td><button className="btn btn-outline-dark btn-sm" onClick={() => edit(c)}>Sửa</button></td></tr>)}</tbody></table></div>{rows.content.length === 0 && <p>Chưa có mã giảm giá.</p>}<button className="btn btn-outline-dark me-2" disabled={!page} onClick={() => setPage(page - 1)}>Trước</button><button className="btn btn-outline-dark" disabled={rows.last} onClick={() => setPage(page + 1)}>Sau</button></> : <p role="status">Đang tải…</p>}</section></>;
}
export function PromotionManager() {
 const [rows, setRows] = useState(null), [products, setProducts] = useState([]), [categories, setCategories] = useState([]), [form, setForm] = useState(blankPromotion), [editing, setEditing] = useState(null), [page, setPage] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('');
 const load = async () => { const [a, p, c] = await Promise.all([api.get('/promotions/manage', { params: { page } }), api.get('/catalog/manage/products', { params: { page: 0, limit: 100 } }), api.get('/catalog/categories')]); setRows(a.data); setProducts(p.data.content); setCategories(c.data); };
 useEffect(() => { load().catch(e => setError(errorMessage(e))); }, [page]);
 const edit = p => { setEditing(p.id); setForm({ ...p, startsAt: dateInput(p.startsAt), endsAt: dateInput(p.endsAt), maximumDiscount: p.maximumDiscount ?? '' }); };
 const save = async e => { e.preventDefault(); setBusy(true); setError(''); setMessage(''); try { const body = { ...inputTime(form), targetId: Number(form.targetId) }; if (editing) await api.put(`/promotions/manage/${editing}`, body); else await api.post('/promotions/manage', body); setForm(blankPromotion()); setEditing(null); setMessage('Đã lưu chương trình khuyến mãi.'); await load(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
 const targets = form.targetType === 'PRODUCT' ? products : categories;
 return <><h1>Khuyến mãi theo sản phẩm / danh mục</h1><Notice error={error} message={message}/><form className="panel mb-4" onSubmit={save}><label className="form-label" htmlFor="offer-name">Tên chương trình</label><input className="form-control mb-3" id="offer-name" required maxLength={120} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/><div className="row g-3"><div className="col-md-4"><label className="form-label" htmlFor="offer-target-type">Áp dụng cho</label><select className="form-select" id="offer-target-type" value={form.targetType} onChange={e => setForm({ ...form, targetType: e.target.value, targetId: '' })}><option value="PRODUCT">Sản phẩm</option><option value="CATEGORY">Danh mục</option></select></div><div className="col-md-8"><label className="form-label" htmlFor="offer-target">Đối tượng</label><select className="form-select" id="offer-target" value={form.targetId} required onChange={e => setForm({ ...form, targetId: e.target.value })}><option value="">Chọn đối tượng</option>{targets.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></div></div><ValueFields form={form} setForm={setForm}/><DateFields form={form} setForm={setForm}/><label className="d-block my-3"><input type="checkbox" className="me-2" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })}/>Đang sử dụng</label><button className="btn btn-primary" disabled={busy}>Lưu chương trình</button>{editing && <button type="button" className="btn btn-link" onClick={() => { setEditing(null); setForm(blankPromotion()); }}>Hủy sửa</button>}</form><section className="panel"><h2>Chương trình đã lưu</h2>{rows ? <><div className="table-responsive"><table className="table"><thead><tr><th>Tên</th><th>Áp dụng</th><th>Giảm</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{rows.content.map(p => <tr key={p.id}><td>{p.name}</td><td>{p.targetType === 'PRODUCT' ? 'Sản phẩm' : 'Danh mục'} · {p.targetId}</td><td>{p.type === 'PERCENT' ? `${p.value}%` : money(p.value)}</td><td>{p.active ? 'Đang bật' : 'Đã tắt'}</td><td><button className="btn btn-outline-dark btn-sm" onClick={() => edit(p)}>Sửa</button></td></tr>)}</tbody></table></div>{rows.content.length === 0 && <p>Chưa có chương trình.</p>}<button className="btn btn-outline-dark me-2" disabled={!page} onClick={() => setPage(page - 1)}>Trước</button><button className="btn btn-outline-dark" disabled={rows.last} onClick={() => setPage(page + 1)}>Sau</button></> : <p role="status">Đang tải…</p>}</section></>;
}
export function ProductReviews({ productId }) {
 const [data, setData] = useState(null), [page, setPage] = useState(0), [stars, setStars] = useState(5), [comment, setComment] = useState(''), [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
 const load = async () => setData((await api.get(`/reviews/products/${productId}`, { params: { page } })).data);
 useEffect(() => { load().catch(e => setError(errorMessage(e))); }, [productId, page]);
 const submit = async e => { e.preventDefault(); setBusy(true); setError(''); setMessage(''); try { await api.post('/reviews', { productId, stars: Number(stars), comment }); setMessage('Đã gửi đánh giá; quản trị viên sẽ duyệt trước khi hiển thị công khai.'); await load(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
 return <section className="panel mt-4"><h2>Đánh giá sản phẩm</h2><Notice error={error} message={message}/>{data ? <>{data.content.length === 0 && <p>Chưa có đánh giá được duyệt.</p>}{data.content.map(r => <article className="border-bottom py-3" key={r.id}><strong>{r.stars}/5 sao</strong><p style={{ whiteSpace: 'pre-wrap' }}>{r.comment}</p><small>{new Date(r.createdAt).toLocaleDateString('vi-VN')}</small></article>)}<button className="btn btn-outline-dark me-2" disabled={!page} onClick={() => setPage(page - 1)}>Trước</button><button className="btn btn-outline-dark" disabled={data.last} onClick={() => setPage(page + 1)}>Sau</button></> : <p role="status">Đang tải đánh giá…</p>}{sessionStorage.getItem('accessToken') ? <form className="mt-4" onSubmit={submit}><h3>Đánh giá sau khi hoàn tất mua hàng</h3><p>Mỗi khách có một đánh giá/sản phẩm. Sửa sẽ đưa đánh giá về trạng thái chờ duyệt.</p><label className="form-label" htmlFor="review-stars">Số sao</label><select className="form-select mb-3" id="review-stars" value={stars} onChange={e => setStars(e.target.value)}>{[5, 4, 3, 2, 1].map(x => <option key={x} value={x}>{x} sao</option>)}</select><label className="form-label" htmlFor="review-comment">Nhận xét</label><textarea className="form-control mb-3" id="review-comment" value={comment} onChange={e => setComment(e.target.value)} required maxLength={1200} rows={4}/><button className="btn btn-primary" disabled={busy}>Gửi đánh giá</button></form> : <p><Link to="/login">Đăng nhập</Link> để đánh giá sản phẩm đã mua.</p>}</section>;
}
export function FavoriteButton({ productId }) {
 const [selected, setSelected] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false);
 useEffect(() => { if (!sessionStorage.getItem('accessToken')) return; api.get('/wishlists').then(r => setSelected(r.data.some(w => w.productId === Number(productId)))).catch(e => setError(errorMessage(e))); }, [productId]);
 if (!sessionStorage.getItem('accessToken')) return <p><Link to="/login">Đăng nhập</Link> để lưu yêu thích.</p>;
 const toggle = async () => { setBusy(true); setError(''); try { if (selected) await api.delete(`/wishlists/${productId}`); else await api.put(`/wishlists/${productId}`); setSelected(!selected); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
 return <div className="my-3"><button className="btn btn-outline-dark" disabled={busy} onClick={toggle}>{selected ? 'Bỏ yêu thích' : 'Thêm vào yêu thích'}</button>{error && <p role="alert" className="text-danger">{error}</p>}</div>;
}
export function WishlistPage() {
 const [rows, setRows] = useState(null), [products, setProducts] = useState({}), [error, setError] = useState(''), [busy, setBusy] = useState(false);
 const load = async () => { const list = (await api.get('/wishlists')).data; setRows(list); const fetched = await Promise.all(list.map(async row => { try { return [row.productId, (await api.get(`/catalog/products/${row.productId}`)).data]; } catch (e) { if (e.response?.status === 404) return [row.productId, null]; throw e; } })); setProducts(Object.fromEntries(fetched)); };
 useEffect(() => { load().catch(e => setError(errorMessage(e))); }, []);
 const remove = async id => { if (!window.confirm('Bỏ sản phẩm khỏi danh sách yêu thích?')) return; setBusy(true); setError(''); try { await api.delete(`/wishlists/${id}`); await load(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
 return <><h1>Sản phẩm yêu thích</h1><Notice error={error}/>{rows ? <section className="panel">{rows.length === 0 && <p>Chưa có sản phẩm yêu thích. <Link to="/">Khám phá bộ sưu tập</Link></p>}{rows.map(r => {
  const p = products[r.productId];
  return <div className="d-flex flex-wrap align-items-center justify-content-between border-bottom py-3 gap-3" key={r.productId}>
   <div className="d-flex align-items-center gap-3">
    {p?.images?.[0]?.url ? <img src={p.images[0].url} alt={p.name} style={{ width: 64, height: 64, objectFit: 'cover', borderRadius: 4 }}/> : <div style={{ width: 64, height: 64, background: '#eee', borderRadius: 4, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, color: '#888' }}>LỤA</div>}
    <div>
     {p ? <strong><Link to={`/products/${r.productId}`}>{p.name}</Link></strong> : `Sản phẩm #${r.productId} đã ngừng bán`}
     {p?.brandName && <small className="d-block text-muted">{p.brandName}</small>}
    </div>
   </div>
   <div className="d-flex align-items-center gap-3">
    {p && <Link to={`/products/${r.productId}`} className="btn btn-outline-primary btn-sm">Xem chi tiết</Link>}
    <button className="btn btn-outline-danger btn-sm" disabled={busy} onClick={() => remove(r.productId)}>Bỏ yêu thích</button>
   </div>
  </div>;
 })}</section> : <p role="status">Đang tải…</p>}</>;
}
export function MyReviewsPage() {
 const [data, setData] = useState(null), [page, setPage] = useState(0), [error, setError] = useState(''), [busy, setBusy] = useState(false);
 const load = async () => setData((await api.get('/reviews/mine', { params: { page } })).data);
 useEffect(() => { load().catch(e => setError(errorMessage(e))); }, [page]);
 const hide = async id => { if (!window.confirm('Ẩn đánh giá của bạn?')) return; setBusy(true); setError(''); try { await api.delete(`/reviews/${id}`); await load(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
 return <><h1>Đánh giá của tôi</h1><Notice error={error}/>{data ? <section className="panel">{data.content.length === 0 && <p>Bạn chưa đánh giá sản phẩm.</p>}{data.content.map(r => <article className="border-bottom py-3" key={r.id}><Link to={`/products/${r.productId}`}>Sản phẩm #{r.productId}</Link><p>{r.stars}/5 sao · {r.state === 'APPROVED' ? 'Đã duyệt' : r.state === 'PENDING' ? 'Chờ duyệt' : 'Đã ẩn'}</p><p style={{ whiteSpace: 'pre-wrap' }}>{r.comment}</p>{r.state !== 'HIDDEN' && <button className="btn btn-outline-danger btn-sm" disabled={busy} onClick={() => hide(r.id)}>Ẩn</button>}</article>)}<button className="btn btn-outline-dark me-2" disabled={!page} onClick={() => setPage(page - 1)}>Trước</button><button className="btn btn-outline-dark" disabled={data.last} onClick={() => setPage(page + 1)}>Sau</button></section> : <p role="status">Đang tải…</p>}</>;
}
export function ReviewManager() {
 const [data, setData] = useState(null), [page, setPage] = useState(0), [state, setState] = useState('PENDING'), [stars, setStars] = useState(''), [productId, setProductId] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
 const load = async () => setData((await api.get('/reviews/manage', { params: { page, ...(state ? { state } : {}), ...(stars ? { stars } : {}), ...(productId ? { productId } : {}) } })).data);
 useEffect(() => { load().catch(e => setError(errorMessage(e))); }, [page, state, stars, productId]);
 const moderate = async (id, status) => { if (!window.confirm(`${status === 'APPROVED' ? 'Duyệt' : 'Ẩn'} đánh giá?`)) return; setBusy(true); setError(''); try { await api.put(`/reviews/manage/${id}`, { state: status }); await load(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
 return <><h1>Duyệt đánh giá</h1><Notice error={error}/><div className="row g-3 mb-4"><div className="col-md-4"><label className="form-label" htmlFor="moderate-state">Trạng thái</label><select className="form-select" id="moderate-state" value={state} onChange={e => { setPage(0); setState(e.target.value); }}><option value="">Tất cả</option><option value="PENDING">Chờ duyệt</option><option value="APPROVED">Đã duyệt</option><option value="HIDDEN">Đã ẩn</option></select></div><div className="col-md-4"><label className="form-label" htmlFor="moderate-stars">Số sao</label><select className="form-select" id="moderate-stars" value={stars} onChange={e => { setPage(0); setStars(e.target.value); }}><option value="">Tất cả</option>{[1, 2, 3, 4, 5].map(x => <option key={x} value={x}>{x}</option>)}</select></div><div className="col-md-4"><label className="form-label" htmlFor="moderate-product">ID sản phẩm</label><input className="form-control" id="moderate-product" type="number" min="1" value={productId} onChange={e => { setPage(0); setProductId(e.target.value); }}/></div></div>{data ? <section className="panel">{data.content.length === 0 && <p>Không có đánh giá phù hợp.</p>}{data.content.map(r => <article className="border-bottom py-3" key={r.id}><p>Sản phẩm #{r.productId} · Khách #{r.userId} · {r.stars}/5 sao · {r.state}</p><p style={{ whiteSpace: 'pre-wrap' }}>{r.comment}</p>{r.state !== 'APPROVED' && <button className="btn btn-outline-dark btn-sm me-2" disabled={busy} onClick={() => moderate(r.id, 'APPROVED')}>Duyệt</button>}{r.state !== 'HIDDEN' && <button className="btn btn-outline-danger btn-sm" disabled={busy} onClick={() => moderate(r.id, 'HIDDEN')}>Ẩn</button>}</article>)}<button className="btn btn-outline-dark me-2" disabled={!page} onClick={() => setPage(page - 1)}>Trước</button><button className="btn btn-outline-dark" disabled={data.last} onClick={() => setPage(page + 1)}>Sau</button></section> : <p role="status">Đang tải…</p>}</>;
}
