import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, errorMessage } from './api';

const states = { REQUESTED: 'Chờ cửa hàng duyệt', APPROVED: 'Đã duyệt, chờ nhận hàng', REJECTED: 'Đã từ chối', RECEIVED: 'Đã nhận hàng, đang đối soát', REFUND_PENDING: 'Đã hoàn kho, chờ hoàn COD thực tế', REFUND_CONFIRMING: 'Đang xác nhận chứng từ hoàn COD', REFUNDED: 'Đã xử lý hoàn tiền' };
const money = value => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(Number(value || 0));
export function ReturnQueue() {
 const [state, setState] = useState('REQUESTED'), [page, setPage] = useState(0), [data, setData] = useState(null), [error, setError] = useState('');
 useEffect(() => { let live=true; setData(null);setError('');api.get('/orders/returns/manage',{params:{page,...(state?{state}:{})}}).then(r=>{if(live)setData(r.data);}).catch(e=>{if(live)setError(errorMessage(e));});return()=>{live=false;};},[state,page]);
 return <><h1>Yêu cầu trả hàng</h1><p>Chọn yêu cầu để xem đơn, duyệt, xác nhận nhận hàng hoặc ghi chứng từ hoàn COD theo quyền.</p><label htmlFor="return-state" className="form-label">Trạng thái yêu cầu</label><select id="return-state" className="form-select mb-4" value={state} onChange={e=>{setState(e.target.value);setPage(0);}}><option value="">Tất cả</option>{Object.entries(states).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>{error&&<p role="alert" className="alert alert-danger">{error}</p>}{!data&&!error&&<p role="status">Đang tải yêu cầu…</p>}{data&&<section className="panel">{data.content.length===0&&<p>Không có yêu cầu ở trạng thái này.</p>}{data.content.map(r=><article className="border-bottom py-3" key={r.id}><Link to={`/orders/${r.orderId}`}>Đơn {r.orderId}</Link><p>{states[r.state]||r.state} · {new Date(r.createdAt).toLocaleString('vi-VN')}</p><p>{r.reason}</p></article>)}<div className="d-flex gap-3 mt-3"><button className="btn btn-outline-dark" disabled={!page} onClick={()=>setPage(page-1)}>Trước</button><span>Trang {page+1}</span><button className="btn btn-outline-dark" disabled={data.last} onClick={()=>setPage(page+1)}>Sau</button></div></section>}</>;
}
export default function ReturnPanel({ order, manage, admin, owner, onUpdated }) {
 const [data, setData] = useState(null), [missing, setMissing] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false), [attempt, setAttempt] = useState(null);
 const [reason, setReason] = useState(''), [mode, setMode] = useState('FULL'), [quantities, setQuantities] = useState({}), [decisionNote, setDecisionNote] = useState(''), [receiptNote, setReceiptNote] = useState(''), [reference, setReference] = useState('');
 const load = async () => {
  try { const result = await api.get(`/orders/${order.id}/return`); setData(result.data); setMissing(false); setError(''); }
  catch (e) { if (e.response?.status === 404) { setData(null); setMissing(true); } else setError(errorMessage(e)); }
 };
 useEffect(() => { setData(null); setMissing(false); load(); const timer = setInterval(load, 5000); return () => clearInterval(timer); }, [order.id]);
 const run = async (path, body, key) => {
  setBusy(true); setError(''); setMessage('');
  try { const result = await api.post(`/orders/${order.id}/return${path}`, body, key ? { headers: { 'Idempotency-Key': key } } : undefined); setData(result.data); setMissing(false); setAttempt(null); await onUpdated(); setMessage('Đã ghi nhận thao tác. Trạng thái đối soát sẽ tự cập nhật.'); }
  catch (e) { setError(errorMessage(e)); if (e.response?.status >= 400 && e.response?.status < 500) setAttempt(null); }
  finally { setBusy(false); }
 };
 const submitRequest = e => { e.preventDefault(); const items = mode === 'PARTIAL' ? order.items.map(i => ({ variantId: i.variantId, quantity: Number(quantities[i.variantId] || 0) })).filter(i => i.quantity > 0) : [];
  if (mode === 'PARTIAL' && (items.length === 0 || items.reduce((n, i) => n + i.quantity, 0) >= order.items.reduce((n, i) => n + i.quantity, 0))) { setError('Hãy chọn ít nhất một sản phẩm và giữ lại ít nhất một sản phẩm trong đơn.'); return; }
  if (!window.confirm(mode === 'FULL' ? 'Gửi yêu cầu trả toàn bộ đơn hàng?' : 'Gửi yêu cầu trả một phần đơn hàng?')) return;
  const item = attempt || { key: crypto.randomUUID(), body: { reason: reason.trim(), ...(mode === 'PARTIAL' ? { items } : {}) } }; setAttempt(item); run('', item.body, item.key); };
 const action = (path, body, prompt) => { if (window.confirm(prompt)) run(path, body); };
 if (!owner && !manage) return null;
 return <section className="border-top mt-4 pt-4"><h3>Trả hàng và hoàn tiền</h3>
  <p className="text-muted">Áp dụng trong 14 ngày sau hoàn tất; mỗi đơn được gửi một yêu cầu trả toàn bộ hoặc một phần. Hàng phải được cửa hàng nhận và kiểm tra. COD chỉ được ghi đã hoàn sau khi ADMIN nhập mã chứng từ chuyển tiền thực tế.</p>
  {error && <p role="alert" className="alert alert-danger">{error}</p>}{message && <p role="status" className="alert alert-success">{message}</p>}
  {!data && !missing && !error && <p role="status">Đang tải yêu cầu trả hàng…</p>}
  {missing && owner && order.state === 'COMPLETED' && <form onSubmit={submitRequest}><label htmlFor="return-mode" className="form-label">Phạm vi trả hàng</label><select id="return-mode" className="form-select mb-3" value={mode} onChange={e => { setMode(e.target.value); setAttempt(null); }}><option value="FULL">Toàn bộ đơn</option><option value="PARTIAL">Một phần đơn</option></select>{mode === 'PARTIAL' && <div className="mb-3">{order.items.map(i => <label className="d-flex align-items-center justify-content-between gap-3 mb-2" key={i.variantId}><span>{i.productName} · {i.size} · {i.color} (đã mua {i.quantity})</span><input className="form-control" style={{maxWidth: 100}} type="number" min="0" max={i.quantity} step="1" value={quantities[i.variantId] ?? 0} onChange={e => { setQuantities({ ...quantities, [i.variantId]: e.target.value }); setAttempt(null); }}/></label>)}<p className="text-muted">Tiền hoàn tính theo giá và giảm giá tại lúc đặt, không gồm phí vận chuyển. Cửa hàng xác nhận số tiền chính xác.</p></div>}<label htmlFor="return-reason" className="form-label">Lý do trả hàng</label><textarea id="return-reason" className="form-control mb-3" minLength={10} maxLength={500} required value={reason} onChange={e => { setReason(e.target.value); setAttempt(null); }}/><button className="btn btn-outline-danger" disabled={busy}>{busy ? 'Đang gửi…' : 'Gửi yêu cầu trả hàng'}</button>{attempt && <button type="button" className="btn btn-warning ms-2" disabled={busy} onClick={() => run('', attempt.body, attempt.key)}>Kiểm tra lại yêu cầu</button>}</form>}
  {data && <><p><strong>{states[data.state] || data.state}</strong> · {data.mode === 'PARTIAL' ? 'Trả một phần' : 'Trả toàn bộ'} · Số tiền hoàn: {money(data.refundAmount)}</p>{data.mode === 'PARTIAL' && <ul>{data.items.map(i => { const bought=order.items.find(x => x.variantId === i.variantId); return <li key={i.variantId}>{bought?.productName || `Biến thể ${i.variantId}`} · {bought?.size} · {bought?.color}: {i.quantity}</li>; })}</ul>}<p>Lý do: {data.reason}</p>{data.decisionNote && <p>Quyết định: {data.decisionNote}</p>}{data.lastError && <p role="alert" className="alert alert-warning">Đối soát chưa thành công: {data.lastError}</p>}
   {manage && data.state === 'REQUESTED' && <div><label htmlFor="return-decision" className="form-label">Ghi chú quyết định; bắt buộc khi từ chối</label><input id="return-decision" className="form-control mb-2" maxLength={500} value={decisionNote} onChange={e => setDecisionNote(e.target.value)}/><button className="btn btn-primary me-2" disabled={busy} onClick={() => action('/decision', { action: 'APPROVE', note: decisionNote }, 'Duyệt trả hàng và số tiền hoàn hiển thị?')}>Duyệt</button><button className="btn btn-outline-danger" disabled={busy || !decisionNote.trim()} onClick={() => action('/decision', { action: 'REJECT', note: decisionNote }, 'Từ chối yêu cầu trả hàng?')}>Từ chối</button></div>}
   {manage && data.state === 'APPROVED' && <form onSubmit={e => { e.preventDefault(); action('/receive', { note: receiptNote }, 'Đã nhận đủ hàng thực tế? Thao tác này sẽ bắt đầu hoàn kho và xử lý hoàn tiền.'); }}><label htmlFor="return-receipt" className="form-label">Biên bản nhận hàng</label><input id="return-receipt" className="form-control mb-2" required maxLength={500} value={receiptNote} onChange={e => setReceiptNote(e.target.value)}/><button className="btn btn-primary" disabled={busy}>Xác nhận đã nhận hàng</button></form>}
   {admin && data.state === 'REFUND_PENDING' && <form onSubmit={e => { e.preventDefault(); action('/confirm-refund', { reference }, 'Chỉ xác nhận sau khi đã chuyển hoàn đủ tiền COD cho khách. Tiếp tục?'); }}><label htmlFor="refund-reference" className="form-label">Mã chứng từ hoàn COD thực tế</label><input id="refund-reference" className="form-control mb-2" required maxLength={190} value={reference} onChange={e => setReference(e.target.value)}/><button className="btn btn-primary" disabled={busy}>Ghi nhận đã hoàn COD</button></form>}
   <details className="mt-3"><summary>Lịch sử trả hàng</summary><ul>{data.history.map((h, i) => <li key={i}>{new Date(h.createdAt).toLocaleString('vi-VN')} · {states[h.state] || h.state}{h.note ? ` — ${h.note}` : ''}</li>)}</ul></details>
  </>}
 </section>;
}
