import React, { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api, errorMessage } from './api';

const names = { OPEN: 'Mới tiếp nhận', IN_PROGRESS: 'Đang xử lý', WAITING_CUSTOMER: 'Chờ khách phản hồi', RESOLVED: 'Đã giải quyết', CLOSED: 'Đã đóng' };
function Notice({ error, success }) { return <>{error && <p className="alert alert-danger" role="alert">{error}</p>}{success && <p className="alert alert-success" role="status">{success}</p>}</>; }

export function SupportListPage({ manage = false }) {
 const navigate = useNavigate(), [data, setData] = useState(null), [page, setPage] = useState(0), [state, setState] = useState(''), [q, setQ] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [subject, setSubject] = useState(''), [message, setMessage] = useState(''), [attempt, setAttempt] = useState(null);
 const load = async () => { setError(''); try { setData((await api.get(manage ? '/support/manage' : '/support', { params: { page, ...(manage && state ? { state } : {}), ...(manage && q ? { q } : {}) } })).data); } catch (e) { setError(errorMessage(e)); } };
 useEffect(() => { load(); }, [page, state, q, manage]);
 const create = async e => { e.preventDefault(); const next = attempt || { key: crypto.randomUUID(), body: { subject: subject.trim(), message: message.trim() } }; setAttempt(next); setBusy(true); setError(''); try { const r = await api.post('/support', next.body, { headers: { 'Idempotency-Key': next.key } }); setAttempt(null); navigate(`/support/${r.data.ticket.id}`); } catch (e) { setError(errorMessage(e)); if (e.response && e.response.status >= 400 && e.response.status < 500) setAttempt(null); } finally { setBusy(false); } };
 return <><h1>{manage ? 'Xử lý yêu cầu hỗ trợ' : 'Liên hệ và hỗ trợ'}</h1><Notice error={error}/>{!manage && <form className="panel mb-4" onSubmit={create}><h2>Gửi yêu cầu mới</h2><label className="form-label" htmlFor="support-subject">Chủ đề</label><input id="support-subject" className="form-control mb-3" required minLength={5} maxLength={160} disabled={!!attempt} value={subject} onChange={e => setSubject(e.target.value)}/><label className="form-label" htmlFor="support-message">Nội dung</label><textarea id="support-message" className="form-control mb-3" required minLength={10} maxLength={4000} rows={5} disabled={!!attempt} value={message} onChange={e => setMessage(e.target.value)}/>{attempt && <p className="alert alert-warning">Chưa rõ kết quả gửi. Thử lại với cùng mã yêu cầu để tránh tạo trùng; bạn cũng có thể kiểm tra danh sách bên dưới.</p>}<button className="btn btn-primary" disabled={busy}>{busy ? 'Đang gửi…' : attempt ? 'Kiểm tra lại yêu cầu' : 'Gửi yêu cầu'}</button></form>}{manage && <div className="row g-3 mb-4"><div className="col-md-5"><label htmlFor="support-filter" className="form-label">Trạng thái</label><select id="support-filter" className="form-select" value={state} onChange={e => { setState(e.target.value); setPage(0); }}><option value="">Tất cả</option>{Object.entries(names).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></div><div className="col-md-7"><label htmlFor="support-search" className="form-label">Tìm chủ đề</label><input id="support-search" className="form-control" value={q} maxLength={100} onChange={e => { setQ(e.target.value); setPage(0); }}/></div></div>}{!data && !error && <p role="status">Đang tải yêu cầu hỗ trợ…</p>}{data && <section className="panel"><h2>Danh sách yêu cầu</h2>{data.content.length === 0 && <p>Chưa có yêu cầu phù hợp.</p>}{data.content.map(t => <article className="border-bottom py-3" key={t.id}><Link to={`/support/${t.id}`}>#{t.id} — {t.subject}</Link><p className="mb-0">{names[t.state]} · {new Date(t.updatedAt).toLocaleString('vi-VN')}{manage ? ` · Khách #${t.userId}` : ''}</p></article>)}<div className="d-flex gap-2 mt-3"><button className="btn btn-outline-dark" disabled={!page} onClick={() => setPage(page - 1)}>Trước</button><span>Trang {page + 1}</span><button className="btn btn-outline-dark" disabled={data.last} onClick={() => setPage(page + 1)}>Sau</button></div></section>}</>;
}

export function SupportDetailPage({ manage = false }) {
 const { id } = useParams(), [data, setData] = useState(null), [message, setMessage] = useState(''), [attempt, setAttempt] = useState(null), [error, setError] = useState(''), [success, setSuccess] = useState(''), [busy, setBusy] = useState(false);
 const load = async () => setData((await api.get(`/support/${id}`)).data);
 useEffect(() => { setData(null); setError(''); load().catch(e => setError(errorMessage(e))); }, [id]);
 const reply = async e => { e.preventDefault(); const next = attempt || { key: crypto.randomUUID(), body: { message: message.trim() } }; setAttempt(next); setBusy(true); setError(''); setSuccess(''); try { const r = await api.post(`/support/${id}/messages`, next.body, { headers: { 'Idempotency-Key': next.key } }); setData(r.data); setMessage(''); setAttempt(null); setSuccess('Đã gửi phản hồi.'); } catch (e) { setError(errorMessage(e)); if (e.response && e.response.status >= 400 && e.response.status < 500) setAttempt(null); } finally { setBusy(false); } };
 const change = async state => { if (!window.confirm(`Chuyển yêu cầu sang “${names[state]}”?`)) return; setBusy(true); setError(''); setSuccess(''); try { const r = await api.put(`/support/${id}/state`, { state }); setData(r.data); setSuccess('Đã cập nhật trạng thái.'); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
 return <><Link to={manage ? '/manage/support' : '/support'}>← Danh sách hỗ trợ</Link><h1 className="mt-3">Chi tiết yêu cầu #{id}</h1><Notice error={error} success={success}/>{!data && !error && <p role="status">Đang tải…</p>}{data && <><section className="panel mb-4"><h2>{data.ticket.subject}</h2><p>Trạng thái: <strong>{names[data.ticket.state]}</strong> · Tạo lúc {new Date(data.ticket.createdAt).toLocaleString('vi-VN')}</p>{manage && <p>Khách hàng #{data.ticket.userId}</p>}<div className="d-flex flex-wrap gap-2">{manage && ['OPEN', 'WAITING_CUSTOMER', 'RESOLVED'].includes(data.ticket.state) && <button className="btn btn-outline-dark" disabled={busy} onClick={() => change('IN_PROGRESS')}>Tiếp nhận / xử lý lại</button>}{manage && ['OPEN', 'IN_PROGRESS', 'WAITING_CUSTOMER'].includes(data.ticket.state) && <button className="btn btn-primary" disabled={busy} onClick={() => change('RESOLVED')}>Đánh dấu đã giải quyết</button>}{data.ticket.state === 'RESOLVED' && <button className="btn btn-outline-dark" disabled={busy} onClick={() => change('CLOSED')}>Đóng yêu cầu</button>}</div></section><section className="panel mb-4"><h2>Trao đổi</h2>{data.messages.map(m => <article className="border-bottom py-3" key={m.id}><strong>{m.authorRole === 'CUSTOMER' ? 'Khách hàng' : m.authorRole === 'ADMIN' ? 'Quản trị viên' : 'Nhân viên'}</strong><small className="ms-2">{new Date(m.createdAt).toLocaleString('vi-VN')}</small><p style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{m.message}</p></article>)}{data.ticket.state !== 'CLOSED' && !(manage && data.ticket.state === 'RESOLVED') && <form className="mt-4" onSubmit={reply}><label className="form-label" htmlFor="support-reply">{manage ? 'Phản hồi khách hàng' : 'Gửi thêm thông tin'}</label><textarea id="support-reply" className="form-control mb-3" rows={4} required maxLength={4000} disabled={!!attempt} value={message} onChange={e => setMessage(e.target.value)}/>{attempt && <p className="alert alert-warning">Chưa rõ kết quả gửi. Thử lại với cùng mã yêu cầu.</p>}<button className="btn btn-primary" disabled={busy}>{busy ? 'Đang gửi…' : 'Gửi phản hồi'}</button></form>}</section><section className="panel"><h2>Lịch sử trạng thái</h2><ol>{data.history.map((h, n) => <li key={n}>{names[h.state]} · {new Date(h.createdAt).toLocaleString('vi-VN')}</li>)}</ol></section></>}</>;
}
